apiVersion: v1
kind: Service
metadata:
  name: microservice-two-service-name
  labels:
    app: microservice-two-service-label
spec:
  type: NodePort
  ports:
  - port: 3000
    protocol: TCP
  selector:
    app: microservice-two-pod-label