apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice-two
  labels:
    app: microservice-two
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microservice-two
  template:
    metadata:
      labels:
        app: microservice-two
    spec:
      imagePullSecrets:
        - name: iemFHvTS1in+I60kJs6mMqEEDqHnu8P3EVHKEA8r
      containers:
        - name: microservice-two-container
          image: microservice-two
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: microservice-one-config
