apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice-two-deployment-name
  labels:
    app: microservice-two-deployment-label
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microservice-two-pod-label
  template:
    metadata:
      labels:
        app: microservice-two-pod-label
    spec:
      imagePullSecrets:
      - name: iemFHvTS1in+I60kJs6mMqEEDqHnu8P3EVHKEA8r
      containers:
      - name: microservice-two-container-name
        image: microservice-two
        ports:
        - containerPort: 3000
