apiVersion: v1
kind: Service
metadata:
  name: microservice-two-service
  labels:
    app: microservice-two-service
spec:
  type: NodePort
  ports:
  - port: 3000
    protocol: TCP
  selector:
    app: microservice-two-pod