---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice-one
  labels:
    app: microservice-one
spec:
  selector:
    matchLabels:
      app: microservice-one-pod
  template:
    metadata:
      labels:
        app: microservice-one-pod
    spec:
      imagePullSecrets:
        - name: iemFHvTS1in+I60kJs6mMqEEDqHnu8P3EVHKEA8r
      containers:
        - name: microservice-one-container
          image: microservice-one
          ports:
            - containerPort: 3000
          envFrom:
            - secretRef:
                name: microservice-one-secret
            - configMapRef:
                name: microservice-one-config
