---
apiVersion: v1
kind: Service
metadata:
  name: microservice-one-service
  labels:
    app: microservice-one-service
spec:
  type: NodePort
  ports:
  - port: 3000
    protocol: TCP
  selector:
    app: microservice-one-pod
