apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: staging
nameSuffix: -staging
resources:
  - ../../base
  - ./namespace.yaml
  - ./ingress.yaml
  - ./microservice-one-config-map.yaml
  - ./microservice-two-config-map.yaml
replicas:
  - count: 1
    name: microservice-one-deployment-name
images:
  - name: microservice-one
    newName: ghcr.io/dinoradulovic/k8s-microservice-one-staging # {"$imagepolicy": "flux-system:microservice-one-staging:name"}
    newTag: tmstp-1651294870 # {"$imagepolicy": "flux-system:microservice-one-staging:tag"}
  - name: microservice-two
    newName: ghcr.io/dinoradulovic/k8s-microservice-two-staging # {"$imagepolicy": "flux-system:microservice-two-staging:name"}
    newTag: tmstp-1651124996 # {"$imagepolicy": "flux-system:microservice-two-staging:tag"}
